### ISSUE TITLE
[Documentation] Capture custom blender runner stuff

### ISSUE THREAD

**Issue by sabhiram** [recogni/blender-scripts#5]
Running blender (custom etc) with our server:
```
<path/to/blender> --background --python-exit-code 1 --python server.py -- --port 8137 --seed 0
```

Sending commands:
```
$ http post localhost:8137 cmd=query_devices
HTTP/1.0 200 OK
Content-Type: application/json
Date: Thu, 05 Dec 2019 22:50:23 GMT
Server: BaseHTTP/0.6 Python/3.7.4

{
    "response": [
        {
            "enabled": false,
            "name": "Intel Core i9-9880H CPU @ 2.30GHz",
            "type": "CPU"
        },
        {
            "enabled": false,
            "name": "Intel Core i9-9880H CPU @ 2.30GHz",
            "type": "CPU"
        }
    ],
    "status": "OK"
}
```

If there is a GPU attached, you will see that in there w/ the type set to `CUDA` then `OpenGL`.

**Comment by caseyberg** [comment]
Response:  [{'name': 'GeForce RTX 2080 Ti', 'type': 'CUDA', 'enabled': True}, {'name': 'AMD Ryzen Threadripper 2970WX 24-Core Processor', 'type': 'CPU', 'enabled': False}, {'name': 'GeForce RTX 2080 Ti', 'type': 'OPTIX', 'enabled': True}]

**Comment by berendo** [comment]
> On a device w/ a RTX2080 (CUDA + OPTIX) here is the same response:

Nice! Thanks, guys. Let me see if I can get the equivalent from inside the container with our custom build...

**Comment by berendo** [comment]
After [this](https://github.com/recogni/blender/commit/1a3f1b0558ab63322371474b07395389673c356b) commit, with our custom Blender container running on a Google Cloud instance with an Nvidia Tesla T4 GPU:
```
berend@berend-test-1:~$ http post localhost:8137 cmd=query_devices
HTTP/1.0 200 OK
Content-Type: application/json
Date: Wed, 11 Dec 2019 07:50:35 GMT
Server: BaseHTTP/0.6 Python/3.7.4
{
    "response": [
        {
            "enabled": true,
            "name": "Tesla T4",
            "type": "CUDA"
        },
        {
            "enabled": true,
            "name": "Tesla T4",
            "type": "OPTIX"
        },
        {
            "enabled": false,
            "name": "Intel Xeon CPU @ 2.20GHz",
            "type": "CPU"
        }
    ],
    "status": "OK"
}
```
